version: '3.7'

# ELK: Elasticsearch - Logstash - Kibana
services:
  Elasticsearch:
    image: elasticsearch:7.17.24
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  Kibana:
    image: kibana:7.17.24
    ports:
      - '5601:5601'
  Logstash:
    image: logstash:7.17.24
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: .
        target: /usr/share/logstash/pipeline
        read_only: true
